# save/exit, then:
git add .github/workflows/ai-build.yml
git commit -m "fix: proper setup-node step (ai-build)"
git push --force-with-lease origin chore/ci-automation
name: AI Build & Review (CrewAI + Claude/OpenAI)

on:
  push:
    branches: ["design-refresh"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ai_build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install CrewAI & SDKs
        run: |
          python -m pip install --upgrade pip
          pip install crewai openai anthropic tiktoken

      - name: Run CrewAI pipeline
        run: python .github/crews/run_crews.py

      - name: JS install & checks (best-effort)
        run: |
          if [ -f package.json ]; then
            corepack enable || true
            if command -v pnpm >/dev/null 2>&1 && [ -f pnpm-lock.yaml ]; then
              pnpm install --frozen-lockfile
              pnpm run lint || true
              pnpm run typecheck || true
              pnpm test || true
            else
              npm ci
              npm run lint || true
              npm run typecheck || true
              npm test || true
            fi
          fi

      - name: Create/Update PR → main
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "automation/ai-build"
          base: "main"
          title: "Automation: design refresh & AI build"
          commit-message: "automation: design refresh & AI build"
          body: |
            This PR was created by the AI Build pipeline.
            - Figma tokens synced
            - Locofy/TeleportHQ scaffolds updated
            - CrewAI suggestions applied
          labels: |
            automation
            design-sync
          delete-branch: true
